import { Palette, HorizontalBox } from "std-widgets.slint";
export component ValueField {
	preferred-height: 100%;
	preferred-width: 100%;
	label: "Label";
	um: "um";
    in property <float> value;
	in property <string> label;
	in property <string> um;
	HorizontalBox {
		width: 100%;
		height: 100%;
		spacing: 0px;
		Text {
			text: label;
			color: Palette.foreground;
			font-size: 20px;
			width: 33%;
			height: 33%;
		}
		Text {
			text: value;
			font-size: 20px;
			color: Palette.accent-background;
			horizontal-alignment: center;
			width: 33%;
			height: 33%;
		}
		Text {
			text: um;
			font-size: 20px;
			width: 33%;
			height: 33%;
		}
	}

}
